plugins:
  communitarian_enabled:
    default: true
    client: true
  communitarian_resolutions_close:
    default: true
    client: true
  communitarian_resolutions_close_week_day:
    default: Sunday
    client: true
    type: enum
    choices:
      - Sunday
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
      - Saturday
  communitarian_resolutions_close_hour:
    default: 12
    client: true
    min: 0
    max: 23
  communitarian_resolutions_reopen_delay:
    default: 1
    client: true
    min: 1
  post_delay:
    default: 300
    client: true
  landing_categories:
    type: category_list
    default: ""
    client: true
  sign_up_with_credit_card_enabled:
    default: true
    client: true
  sign_up_with_stripe_identity_enabled:
    default: true
    client: true
  linkedin_enabled:
    client: true
    default: false
  linkedin_client_id:
    client: false
    default: ""
  linkedin_secret:
    client: false
    default: ""
  communitarian_stripe_secret_key:
    default: ""
    secret: true
  communitarian_stripe_public_key:
    default: ""
    client: true
    secret: true
  socials_twitter_url:
    client: true
    default: "https://twitter.com/civildialogues"
  socials_facebook_url:
    client: true
    default: "https://www.facebook.com/Civildialoguesorg-106269701225894/"
  about_title:
    client: true
    default: "About Civil Dialogues"
  community_code_maxlength:
    client: true
    default: 5
