name: Quality

on: [push]

jobs:
  test:
    env:
      POSTGRES_HOST: localhost
      POSTGRES_USER: discourse
      POSTGRES_PASSWORD: discourse
      RAILS_ENV: test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_HOST: localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cache:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
    - name: Clone Discourse (stable)
      uses: actions/checkout@v2
      with:
        repository: 'discourse/discourse'
        ref: 'stable'
    - name: Clone communitarian-discourse-plugin
      uses: actions/checkout@v2
      with:
        path: plugins/communitarian
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Cache bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Migrate database
      run: bundle exec rake db:create db:migrate
    - name: Run Communitarian tests
      run: bundle exec rails plugin:spec[communitarian]
