name: Quality

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: discourse
      PGPASSWORD: discourse
      DISCOURSE_HOSTNAME: www.example.com
      RUBY_GLOBAL_METHOD_CACHE_SIZE: 131072

    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: discourse
          POSTGRES_PASSWORD: discourse
          POSTGRES_DB: discourse_test
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cache:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
    - name: Clone Discourse (stable)
      uses: actions/checkout@v2
      with:
        repository: 'discourse/discourse'
        ref: 'stable'

    - name: Clone communitarian-discourse-plugin
      uses: actions/checkout@v2
      with:
        path: plugins/communitarian

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Restore bundle from cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Install dependencies
      run: bundle install --path='./vendor/bundle'

    - name: Cache bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gems-

    - name: Migrate database
      run: bundle exec rake db:create db:migrate

    - name: Run Communitarian tests
      run: bundle exec rails plugin:spec[communitarian]
